// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RoleGeneratorSpace
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System.Configuration;
    using RoleGeneratorSpace;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class UpdaterRuntimeTemplate : UpdaterRuntimeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.Updating;
using DevExpress.Persistent.Base;
");
            
            #line 20 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"

foreach(string nameSpace in NameSpacesCodeLines){
            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 22 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nameSpace));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 23 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
namespace YourNameSpace {
	public class RoleUpdater : ModuleUpdater {
		public RoleUpdater(IObjectSpace objectSpace, Version currentDBVersion) :
			base(objectSpace, currentDBVersion) {
		}
		public override void UpdateDatabaseAfterUpdateSchema() {
			base.UpdateDatabaseAfterUpdateSchema();
");
            
            #line 32 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"

foreach(var method in CodeLines){
            
            #line default
            #line hidden
            this.Write("\t\t\tCreate");
            
            #line 34 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Key));
            
            #line default
            #line hidden
            this.Write("Role();\r\n");
            
            #line 35 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tObjectSpace.CommitChanges();\r\n\t\t}\r\n");
            
            #line 38 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"

foreach(var method in CodeLines){
            
            #line default
            #line hidden
            this.Write("\t\tpublic void Create");
            
            #line 40 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Key));
            
            #line default
            #line hidden
            this.Write("Role() {\r\n\t\t\t");
            
            #line 41 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RoleTypeName));
            
            #line default
            #line hidden
            this.Write(" role = ObjectSpace.FindObject<");
            
            #line 41 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RoleTypeName));
            
            #line default
            #line hidden
            this.Write(">(new BinaryOperator(\"Name\", \"");
            
            #line 41 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Key));
            
            #line default
            #line hidden
            this.Write("\"));\r\n\t\t\tif(role == null) {\r\n\t\t\t\trole = ObjectSpace.CreateObject<");
            
            #line 43 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(RoleTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 44 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"

	foreach(string codeLine in method.Value){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 46 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codeLine));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 47 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n");
            
            #line 50 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"
}
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "E:\Projects\RoleGeneratorRepo\RoleGenerator\UpdaterRuntimeTemplate.tt"

private global::System.Collections.Generic.HashSet<System.String> _NameSpacesCodeLinesField;

/// <summary>
/// Access the NameSpacesCodeLines parameter of the template.
/// </summary>
private global::System.Collections.Generic.HashSet<System.String> NameSpacesCodeLines
{
    get
    {
        return this._NameSpacesCodeLinesField;
    }
}

private global::System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>> _CodeLinesField;

/// <summary>
/// Access the CodeLines parameter of the template.
/// </summary>
private global::System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>> CodeLines
{
    get
    {
        return this._CodeLinesField;
    }
}

private string _RoleTypeNameField;

/// <summary>
/// Access the RoleTypeName parameter of the template.
/// </summary>
private string RoleTypeName
{
    get
    {
        return this._RoleTypeNameField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool NameSpacesCodeLinesValueAcquired = false;
if (this.Session.ContainsKey("NameSpacesCodeLines"))
{
    this._NameSpacesCodeLinesField = ((global::System.Collections.Generic.HashSet<System.String>)(this.Session["NameSpacesCodeLines"]));
    NameSpacesCodeLinesValueAcquired = true;
}
if ((NameSpacesCodeLinesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("NameSpacesCodeLines");
    if ((data != null))
    {
        this._NameSpacesCodeLinesField = ((global::System.Collections.Generic.HashSet<System.String>)(data));
    }
}
bool CodeLinesValueAcquired = false;
if (this.Session.ContainsKey("CodeLines"))
{
    this._CodeLinesField = ((global::System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>>)(this.Session["CodeLines"]));
    CodeLinesValueAcquired = true;
}
if ((CodeLinesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("CodeLines");
    if ((data != null))
    {
        this._CodeLinesField = ((global::System.Collections.Generic.Dictionary<System.String, System.Collections.Generic.List<System.String>>)(data));
    }
}
bool RoleTypeNameValueAcquired = false;
if (this.Session.ContainsKey("RoleTypeName"))
{
    this._RoleTypeNameField = ((string)(this.Session["RoleTypeName"]));
    RoleTypeNameValueAcquired = true;
}
if ((RoleTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("RoleTypeName");
    if ((data != null))
    {
        this._RoleTypeNameField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class UpdaterRuntimeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
